apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache2
  name: apache2
spec:
  ports:
  - port: 80
    Nodeport: 30010
    targetPort: 80
  selector:
    app: apache2
  type: NodePort
status:
  loadBalancer: {}
